README.md

Hey
I hope this serves the purpose for contributors list.
I'd be glad to make any further changes if you suggest any.
Thanks!

Git checkout- Contributors section

---

Projects/abdul-azeez060-petAdoptation/PetAdoptation.css
Projects/abdul-azeez060-petAdoptation/PetAdoptation.html

PetAdoptation page

---

src/Contributer/User.js

add new pr

---

src/Components/Profile.css
src/Components/Profile.jsx
src/Contributer/User.js

Adding Own profile to the home or Profile.jsx file

---

src/Contributer/User.js

adding my name to contributor list user.js

add my name

---

Projects/Todo list app Likeur/app.js
Projects/Todo list app Likeur/index.html
Projects/Todo list app Likeur/style.css
src/Contributer/User.js

adding a todo list project made with html, css and js

add a todo list app to project

---

Projects/dice-app/.eslintrc.cjs
Projects/dice-app/.gitignore
Projects/dice-app/README.md
Projects/dice-app/index.html
Projects/dice-app/package-lock.json
Projects/dice-app/package.json
Projects/dice-app/src/App.css
Projects/dice-app/src/App.jsx
Projects/dice-app/src/Dice.css
Projects/dice-app/src/Dice.jsx
Projects/dice-app/src/index.css
Projects/dice-app/src/main.jsx
Projects/dice-app/vite.config.js

- Created Basic Dice app using react

dice-app using react

---

Projects/abdul-azeez-Sidebar/Sidebar.css
Projects/abdul-azeez-Sidebar/Sidebar.html

Please don't forget to add the hactoberfest-accepted label. I have added my sidebar project.Just like yesterday

Added Sidebar project

---

index.html
script.js
style.css

Added HTML, CSS and JS file of calculator web app

Added calculator app to the repo

---

Code Of Conduct

Code of conduct is added issue #48

Create Code Of Conduct

---

Projects/Digital Clock/index.html
Projects/Digital Clock/script.js
Projects/Digital Clock/styles.css

Digital Clock -> using HTML , CSS , Javascript

Digital Clock - HacktoberFest2023

---

Projects/ATM Project/ATM.java
src/Contributer/User.js

It is console based application created using java

Created ATM Project Using Java

---

Projects/AngularJS Usage/README.md
Projects/AngularJS Usage/app.js
Projects/AngularJS Usage/index.html

Added the simple implementation of the Anugyar JS framework of javascript in Project directory.

Added the simple implementation of Angular JS

---

Projects/The_Calculator-main/README.md
Projects/The_Calculator-main/index.html
Projects/The_Calculator-main/script.js
Projects/The_Calculator-main/style.css
Projects/The_Calculator-main/utils.css

fixes #68 
I have added the Calculator project.

Added Calculator

---

Projects/Clock/Clock.css
Projects/Clock/Clock.html
Projects/Clock/Clock.js
calculator.html
calculatorStyle.css
calculatorjavascript.js

I have added my own practice project which is Clock. Its functionality defines various concepts and enables me to make my own functionality.

Calculator

---

src/Contributer/User.js

Add One more profile Card, to increase the contributors in it

Add One more profile Card

---

Projects/Safiya-siddiqui-filtergallery/Gallery.css
Projects/Safiya-siddiqui-filtergallery/Gallery.html
Projects/Safiya-siddiqui-filtergallery/Gallery.js
src/Contributer/User.js

first task complete

---

Projects/weatherAppUsing-API/index.html
Projects/weatherAppUsing-API/index.js
Projects/weatherAppUsing-API/style.css
src/Contributer/User.js

I  created  a website that fetches weather data and display to frontend using API , i used weatherapi

Weather app using api

---

src/Components/Profile.css
src/Contributer/User.js

Added some styles to the container and button. Perform code review and please merge.

styles cards and buttons

---

Projects/EnglishDictionary-UsingAPI/index.html
Projects/EnglishDictionary-UsingAPI/index.js
Projects/EnglishDictionary-UsingAPI/style.css

I created Website Using Dictionary API that takes english word and return meaning of it

EnglishDictionary-UsingAPI

---

src/Components/Profile.css
src/Components/Profile.jsx
src/Contributer/User.js

Add style to an buttons to make an interactive.

adding some css to buttons

---

Projects/login/form.js
Projects/login/index.html
Projects/login/style.css

I have added a project of login form verification.

login.html

---

src/Contributer/User.js

add user contribute

---

Projects/YT-MP3/index.html
src/Contributer/User.js

- add project
- update user.js

add project

---

src/Contributer/User.js

i have added about myself and my passion and my interests and my linkedin profile

i have added my bio in the uer.js
